apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: darpbr/gitops
  newTag: a538971601420b09355a339c0c482e819ae1eab9
